spring.application.name=10-SB-Redis-App

spring.data.redis.url=rest-sponge-quartzose-91099.db.redis.io:17716
spring.data.redis.port=17716
spring.data.redis.username=default
spring.data.redis.password=fkEJ56f7m5qW9zTepasVn5IkhLAPTbjH
